[build]
  publish = "."
  functions = "functions"
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
