[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "14"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**/*.js"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-core"
  from = "/*"
  to = "/_redirects"
  status = 200
