[build]
  publish = "."
  functions = "functions"
  command = "node -e \"console.log(JSON.parse(require('fs').readFileSync('package.json', 'utf8')))\""

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
