name: Manual Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type (patch, minor, major)"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run tests
        run: npm test

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Release Script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          RELEASE_TYPE: ${{ github.event.inputs.releaseType }}
        run: |
          chmod +x ./release.sh
          ./release.sh
