name: Automated Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check for meaningful changes
        id: check_changes
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          CHANGES=$(git log ${LATEST_TAG}..HEAD --oneline --no-merges --grep="^(?!Bump version)")
          if [ -z "$CHANGES" ]; then
            echo "No meaningful changes since last release. Skipping release."
            echo "::set-output name=should_release::false"
          else
            echo "Meaningful changes found. Proceeding with release."
            echo "::set-output name=should_release::true"
          fi

      - name: Run release script
        id: release
        if: steps.check_changes.outputs.should_release == 'true'
        run: |
          chmod +x ./release.sh
          echo "This is an automated release" | ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check release script output
        if: steps.check_changes.outputs.should_release == 'true'
        run: |
          if [[ ${{ steps.release.outcome }} == 'failure' ]]; then
            echo "Release script failed. Please check the logs for more information."
            exit 1
          fi

      - name: No Release
        if: steps.check_changes.outputs.should_release != 'true'
        run: echo "No new release created as there were no meaningful changes."
