name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

        - name: Install dependencies
          run: npm ci || npm install

        - name: Run tests
          run: npm test

        - name: Commit package-lock.json if changed
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add package-lock.json
            git diff --quiet && git diff --staged --quiet || git commit -m "Update package-lock.json"

        - name: Create Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            npm version patch -m "Bump version to %s"
            git push --follow-tags
            npm run release
