name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Debug - List directory contents
        run: ls -la

      - name: Debug - Print package.json contents
        run: cat package.json

      - name: Debug - Validate package.json
        run: |
          if jq empty package.json >/dev/null 2>&1; then
            echo "package.json is valid JSON"
          else
            echo "package.json is not valid JSON"
            jq empty package.json
          fi

      - name: Debug - Print npm config
        run: npm config list

      - name: Debug - Print npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm version patch -m "Bump version to %s"
          git push --follow-tags
          npm run release
